# Generated by Django 5.1.2 on 2024-11-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("status", models.CharField(default="to_transcribe", max_length=100)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="crowdsourcing.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rectangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("angle", models.FloatField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rectangles",
                        to="crowdsourcing.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="bob", max_length=100)),
                ("stated", models.DateTimeField(auto_now_add=True)),
                ("ended", models.DateTimeField()),
                ("status", models.CharField(default="in_progress", max_length=100)),
                ("type", models.CharField(default="transcription", max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="crowdsourcing.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.TextField(default="")),
                ("status", models.CharField(default="in_progress", max_length=100)),
                (
                    "rectangle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="crowdsourcing.rectangle",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="crowdsourcing.task",
                    ),
                ),
            ],
        ),
    ]
