# Generated by Django 5.1.2 on 2024-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rectangle",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
