# Generated by Django 5.1.2 on 2024-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0003_userproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("verifier", "Verifier"),
                    ("transcriber", "Transcriber"),
                ],
                default="Transcriber",
                max_length=100,
            ),
        ),
    ]
