# Generated by Django 5.1.2 on 2024-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0005_alter_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_transcribe", "To Transcribe"),
                    ("in_transcription", "In Transcription"),
                    ("to_verify", "To Verify"),
                    ("in_verification", "In Verification"),
                    ("completed", "Completed"),
                ],
                default="to_transcribe",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("timeout", "Timeout"),
                ],
                default="in_progress",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("transcription", "Transcription"),
                    ("Verification", "Verification"),
                ],
                default="transcription",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("verifier", "Verifier"),
                    ("transcriber", "Transcriber"),
                    ("candidate", "Candidate"),
                ],
                default="Transcriber",
                max_length=100,
            ),
        ),
    ]
