# Generated by Django 5.1.2 on 2024-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0007_alter_userproject_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("transcription", "Transcription"),
                    ("verification", "Verification"),
                ],
                default="transcription",
                max_length=100,
            ),
        ),
    ]
