# Generated by Django 5.1.2 on 2024-12-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0010_alter_userproject_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("verifier", "Verifier"),
                    ("transcriber", "Transcriber"),
                    ("Candidate", "candidate"),
                    ("block", "Block"),
                ],
                default="Transcriber",
                max_length=100,
            ),
        ),
    ]
