# Generated by Django 5.1.3 on 2025-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0014_alter_userproject_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
