# Generated by Django 5.1.3 on 2025-04-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0015_document_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='feedback',
        ),
    ]
