# Generated by Django 5.1.3 on 2025-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0017_alter_userproject_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('verifier', 'Verifier'), ('transcriber', 'Transcriber'), ('candidate', 'Candidate'), ('block', 'Block')], default='Transcriber', max_length=100),
        ),
    ]
