# Generated by Django 5.1.3 on 2025-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0019_rename_group_name_document_archive_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('verifier', 'Verifier'), ('transcriber', 'Transcriber'), ('Candidate', 'candidate'), ('Block', 'block')], default='Transcriber', max_length=100),
        ),
    ]
