# Generated by Django 5.1.3 on 2025-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0020_alter_userproject_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='stated',
            new_name='started',
        ),
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('verifier', 'Verifier'), ('transcriber', 'Transcriber'), ('Candidate', 'candidate'), ('block', 'Block')], default='Transcriber', max_length=100),
        ),
    ]
