# Generated by Django 5.1.2 on 2024-12-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0012_alter_userproject_role"),
        ("forum", "0038_alter_userpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="related_document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcing.document",
            ),
        ),
        migrations.AddField(
            model_name="userpost",
            name="related_subtask",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcing.subtask",
            ),
        ),
        migrations.DeleteModel(name="Author",),
    ]
