# Generated by Django 5.1.2 on 2024-12-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0013_alter_userproject_role"),
        ("forum", "0039_userpost_related_document_userpost_related_subtask_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userpost", name="related_subtask",),
        migrations.AddField(
            model_name="userpost",
            name="related_rectangle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcing.rectangle",
            ),
        ),
    ]
