# Generated by Django 5.1.2 on 2024-12-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcing", "0014_alter_userproject_role"),
        ("forum", "0040_remove_userpost_related_subtask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="related_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcing.document",
            ),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="related_rectangle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crowdsourcing.rectangle",
            ),
        ),
    ]
