# Generated by Django 5.1.3 on 2025-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0041_alter_userpost_related_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
