# Generated by Django 5.1.3 on 2025-05-05 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0020_alter_userproject_role'),
        ('forum', '0042_remove_blogpost_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='UserPost',
            new_name='Topic',
        ),
    ]
